import { GoogleGenAI } from "@google/genai";

const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

export interface MarketInsight {
  text: string;
  sources: Array<{
    web?: {
      uri: string;
      title: string;
    }
  }>;
}

export const generateAuctionDescription = async (title: string, specs: string): Promise<string> => {
  if (!apiKey) {
    console.warn("API_KEY is missing. Returning mock response.");
    return "This is a detailed description generated by AI (Mock) because the API Key is missing. Ideally, this would describe the features, condition, and value proposition of the item.";
  }

  try {
    const model = 'gemini-2.5-flash';
    const prompt = `Write a compelling, professional auction description (approx 100 words) for the following item:
    Title: ${title}
    Specifications: ${specs}
    
    Highlight key features and attract potential bidders.`;

    const response = await ai.models.generateContent({
      model,
      contents: prompt,
    });

    return response.text || "No description generated.";
  } catch (error) {
    console.error("Error generating description:", error);
    return "Failed to generate description. Please try again later.";
  }
};

export const estimatePrice = async (details: string): Promise<string> => {
    if (!apiKey) return "Estimate unavailable (No Key)";
    
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: `Based on these details, provide a rough estimated price range for an auction starting price. Output ONLY the range (e.g., "$10,000 - $15,000"). Details: ${details}`
        });
        return response.text || "Unavailable";
    } catch (e) {
        return "Unavailable";
    }
};

export const getMarketInsights = async (query: string): Promise<MarketInsight | null> => {
  if (!apiKey) return null;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Perform a real-time market analysis for "${query}" in the context of current auctions (2024-2025). 
      
      Provide:
      1. Current market sentiment (Hot/Cold/Stable).
      2. Recent notable sales or price trends.
      3. Key features buyers are currently looking for.
      
      Keep it concise (max 150 words).`,
      config: {
        tools: [{ googleSearch: {} }],
      },
    });

    const text = response.text || "No insights available.";
    const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];

    return { text, sources };
  } catch (error) {
    console.error("Market insight error:", error);
    return null;
  }
};

export const validateAddress = async (address: string): Promise<string | null> => {
  if (!apiKey) return null;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Verify this address/location and format it as a standard single-line address string: "${address}". If it's ambiguous, return the most likely specific location.`,
      config: {
        tools: [{ googleMaps: {} }],
      },
    });
    
    return response.text?.trim() || null;
  } catch (error) {
    console.error("Address validation error:", error);
    return null;
  }
};

export const searchPlaces = async (query: string): Promise<string[]> => {
  if (!apiKey) return [];

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `Find up to 5 real-world locations (cities or specific addresses) that match the query "${query}". Return ONLY the address strings, one per line. Do not include numbering, bullets, or extra text.`,
      config: {
        tools: [{ googleMaps: {} }],
      },
    });
    
    const text = response.text || "";
    // Filter out empty lines and potential markdown artifacts
    return text.split('\n')
      .map(line => line.trim())
      .filter(line => line.length > 0 && !line.startsWith('```'));
  } catch (error) {
    console.error("Place search error:", error);
    return [];
  }
};